name: CMake

# Do not use any other type of trigger here. Using a pull-request trigger in public
# repos allows anyone to fork / create a pull request and run malicious code on
# the runner.
on: [push]

env:
  BUILD_TYPE: Release
  PSExecutionPolicyPreference: Unrestricted

jobs:
  build_and_test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake %GITHUB_WORKSPACE% -DCMAKE_BUILD_TYPE=%BUILD_TYPE%

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: cmd
      run: cmake --build . --config %BUILD_TYPE%

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: cmd
      run: ctest -C %BUILD_TYPE%
